### PR TITLE
feat: render schedule from svg

### PR DESCRIPTION
**Pull request by thisisfabrics**
### Description of changes
The form_schedule function for PIL schedule images has been changed. The previous implementation was removed including attendant functions and replaced with a single svg string. Inside resourses, the template was placed. 
The cairosvg library for svg converting to png was added.

Some function signatures were changed to enable or disable the fill of cells of a schedule image.

_render_keyboard was changed to correct alignment of buttons when all timeslots are visible.

The Roboto font has to be installed on the server!
image

### CODE REVIEW

**Comment by ArtemSBulgakov** [comment]
Deployed to https://t.me/InnoMusicRoomStagingBot

@dantetemplar You can review it

**Comment by dantetemplar** [comment]
> Deployed to https://t.me/InnoMusicRoomStagingBot
> 
> @dantetemplar You can review it

It seems to be old images

image

**Comment by ArtemSBulgakov** [comment]
> > Deployed to https://t.me/InnoMusicRoomStagingBot
> > @dantetemplar You can review it
> 
> It seems to be old images

You are too late. Deploy the API and bot again if you want to check it on staging.

**Comment by ArtemSBulgakov** [comment]
Resolved conflicts with new pyproject.

**Pull request merged**
